Algoritmo "temperaturaCelsius"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : Converter Celsius em Fahrenheit! (temperaturaCelsius)
// Autor(a)    : Bernardo Prieto
// Data atual  : 30/08/2023
Var
celsius: real
fahrenheit: real
Inicio
escreva("Insira a temperatura em Celsius para Fahrenheit")
leia(celsius)
fahrenheit<-(celsius*9)/5 +32
escreva("A temperatura em fahrenheit é de: ", fahrenheit)

Fimalgoritmo