Algoritmo "cronômetro"
// Disciplina   : [ Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : laço de repetição "para" cronômetro! (cronômetro)
// Autor(a)    : Bernardo Prieto
// Data atual  : 18/09/2023
Var
   contadora, contadora1:inteiro



Inicio
   para contadora de 0 ate 59 passo 1 faca
      para contadora1 de 0 ate 59 passo 1 faca
         escreval(contadora," : ", contadora1)
      fimpara
   fimpara



Fimalgoritmo