Algoritmo "Divisão"
// Disciplina   :[Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : Divisão de dois números! (dividir)
// Autor(a)    : Bernardo M.D.Prieto
// Data atual  : 30/08/2023
Var
valor01: inteiro
valor02: inteiro
divisao: real

Inicio
Escreva("Escreva o primeiro número da divisão")
leia(valor01)
Escreva("Escreva o segundo número da divisão")
leia(valor02)
divisao<-valor01/valor02
escreva("O valor da divisão é: ", divisao)

Fimalgoritmo