Algoritmo "ESPRESSAO1"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : Expressão em forma de sintaxe (Expressões)
// Autor(a)    : Bernardo Prieto
// Data atual  : 04/09/2023
Var
numA: inteiro
numB: inteiro
resultado: real


Inicio
escreva("Insira o primeiro número")
leia(numA)
escreva("Insira o segundo número")
leia(numB)
resultado<-numA+(numB/3)
escreva("O resultado é: ", resultado)


Fimalgoritmo