Algoritmo "temperaturaFahrenheit"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : Converter Celsius em Fahrenheit! (temperaturaCelsius)
// Autor(a)    : Bernardo Prieto
// Data atual  : 30/08/2023
Var
celsius: real
fahrenheit: real
Inicio
escreva("Insira a temperatura em Fahrenheit para Celsius")
leia(fahrenheit)
Celsius<-(fahrenheit-32)*5/9
escreva("A temperatura em Celsius é de: ", Celsius)

Fimalgoritmo