Algoritmo "quadradoDaDiferenca"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : Resolver o quadrado da diferença de dois termos!
//(QuadradoDaDiferenca)
// Autor(a)    : Bernardo
// Data atual  : 01/09/2023
Var
valorA: inteiro
valorB: inteiro

Inicio
escreva("informe primeiro o valor A e depois o valor B")
leia(valorA)
leia(valorB)
escreva("O quadrado da diferença de A por B é: ", (valorA - valorB)^2)

Fimalgoritmo